Models/ErrorViewModel.cs
namespace construplan_examen.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/OrdenDeCompra.cs
using System.ComponentModel.DataAnnotations;

namespace construplan_examen.Models
{
    public class OrdenDeCompra
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El Numero de Orden es obligatorio")]
        [StringLength(20)] 
        [RegularExpression(@"^\d+$")]
        public string NumeroDeOrden { get; set; } = string.Empty; 

        [Required(ErrorMessage = "La fecha es obligatoria.")]
        public DateTime? Fecha { get; set; }

        [Required(ErrorMessage = "El Proveedor es obligatorio")]
        public string Proveedor { get; set; } = string.Empty;

        [Required(ErrorMessage = "El Monto Total es obligatorio")]
        [Range(1, double.MaxValue, ErrorMessage = "El monto debe ser mayor a 0.")]
        public decimal MontoTotal { get; set; }
    }
}

Models/OrdenDeCompraViewModel.cs
namespace construplan_examen.Models
{
    public class OrdenDeCompraViewModel
    {
        public OrdenDeCompra Orden { get; set; } = new OrdenDeCompra();
        public string FormAction { get; set; } = "Create";
    }

}

Models/ServiceResult.cs
namespace construplan_examen.Models
{
    public enum ErrorType
    {
        None,
        NotFound,
        Validation,
        Conflict,
        ActionError,
        Unexpected,
    }

    public class ServiceResult<T>
    {
        public bool Success { get; set; }
        public string Message { get; set; } = string.Empty;
        public ErrorType ErrorType { get; set; } = ErrorType.None;
        public T? Data { get; set; }

        public static ServiceResult<T> Ok(T data, string message = "")
        {
            return new ServiceResult<T> { Success = true, Message = message, Data = data };
        }

        public static ServiceResult<T> OkAction(T data, string action, string fieldName)
        {
            return new ServiceResult<T> { Success = true, Message = $"Exito al {action} la {fieldName} ", Data = data };
        }

        public static ServiceResult<T> OkAction(string action, string fieldName)
        {
            return new ServiceResult<T> { Success = true, Message = $"Exito al {action} la {fieldName} " };
        }

        public static ServiceResult<T> OkFinded(T data, string fieldName)
        {
            return new ServiceResult<T> { Success = true, Message = $"{fieldName} obtenida con exito", Data = data };
        }

        public static ServiceResult<T> Fail(string message, ErrorType error)
        {
            return new ServiceResult<T> { Success = false, Message = message, ErrorType = error };
        }

        public static ServiceResult<T> FailWithData(T data, string message, ErrorType error)
        {
            return new ServiceResult<T> { Success = false, Message = message, ErrorType = error, Data = data };
        }

        public static ServiceResult<T> FailIdNotFound(string fieldName, int id)
        {
            return new ServiceResult<T> { Success = false, Message = $"La ID: {id} no corresponde a alguna {fieldName}", ErrorType = ErrorType.NotFound };
        }

    }
}

Controllers/OrdenDeCompraController.cs
using construplan_examen.Interfaces;
using construplan_examen.Models;
using Microsoft.AspNetCore.Mvc;

public class OrdenDeCompraController : Controller
{
    private readonly IOrdenCompraService _service;

    public OrdenDeCompraController(IOrdenCompraService service)
    {
        _service = service;
    }

    public IActionResult Index()
    {
        ServiceResult<List<OrdenDeCompra>> result = _service.GetAll();

        return View(result.Data);
    }

    [HttpGet]
    public IActionResult Create()
    {
        OrdenDeCompraViewModel ordenViewModel = new OrdenDeCompraViewModel()
        {
            Orden = new OrdenDeCompra(),
            FormAction = "Create",
        };
        return View(ordenViewModel);
    }

    [HttpPost]
    public IActionResult Create(OrdenDeCompraViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMessage"] = "Los datos ingresados no son validos.";
            return View(model);
        }

        ServiceResult<OrdenDeCompra> result = _service.Create(model.Orden);

        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            return View(model);
        }

        TempData["SuccessMessage"] = result.Message;
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        ServiceResult<OrdenDeCompra> result = _service.GetById(id);

        if (result.Data == null || result.Success == false)
        {
            TempData["ErrorMessage"] = result.Message;
            return RedirectToAction("Index");
        }

        return View(new OrdenDeCompraViewModel
        {
            Orden = result.Data,
            FormAction = "Edit"
        });
    }

    [HttpPost]
    public IActionResult Edit(OrdenDeCompraViewModel model)
    {
        if (!ModelState.IsValid)
        {
            TempData["ErrorMessage"] = "Los datos ingresados no son validos.";
            model.FormAction = "Edit";
            return View(model);
        }

        ServiceResult<OrdenDeCompra> result = _service.Update(model.Orden);

        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            model.FormAction = "Edit";
            return View(model);
        }

        TempData["SuccessMessage"] = result.Message;
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        ServiceResult<OrdenDeCompra> result = _service.Delete(id);

        if (!result.Success)
        {
            TempData["ErrorMessage"] = result.Message;
            return RedirectToAction("Index");
        }

        TempData["SuccessMessage"] = "Orden eliminada correctamente.";

        return RedirectToAction("Index");
    }
}

Views/OrdenDeCompra/Create.cshtml
@model OrdenDeCompraViewModel

<div class="row justify-content-center mt-5">
    <div class="col-md-7">

        <div class="card shadow-sm border-0">
            <div class="card-header bg-primary text-white text-center">
                <h5 class="mb-0">Nueva Orden de Compra</h5>
            </div>

            <div class="card-body p-4">
                @await Html.PartialAsync("_OrdenForm", Model)
            </div>
        </div>
    </div>
</div>

Views/OrdenDeCompra/Edit.cshtml
@model OrdenDeCompraViewModel

<div class="row justify-content-center mt-5">
    <div class="col-md-7">

        <div class="card shadow-sm border-0">
            <div class="card-header bg-warning text-dark text-center">
                <h5 class="mb-0">Editar Orden de Compra</h5>
            </div>

            <div class="card-body p-4">
                @await Html.PartialAsync("_OrdenForm", Model)
            </div>
        </div>
    </div>
</div>

Views/OrdenDeCompra/Index.cshtml
@model IEnumerable<OrdenDeCompra>

@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Bienvenido al CRUD </h1>
    </div>

    <partial name="_tableOrdenCompra" model=Model />

Views/OrdenDeCompra/_OrdenForm.cshtml
@model OrdenDeCompraViewModel

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}

<form asp-controller="OrdenDeCompra"
      asp-action="@Model.FormAction"
      method="post">

    <input type="hidden" asp-for="Orden.Id" />

    <div class="mb-3">
        <label asp-for="Orden.NumeroDeOrden" class="form-label fw-bold">Numero de Orden</label>
        <input asp-for="Orden.NumeroDeOrden" class="form-control" type="number" value=@Model.Orden.NumeroDeOrden />
        <span asp-validation-for="Orden.NumeroDeOrden" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Orden.Proveedor" class="form-label fw-bold">Proveedor</label>
        <input asp-for="Orden.Proveedor" class="form-control" value=@Model.Orden.Proveedor />
        <span asp-validation-for="Orden.Proveedor" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Orden.MontoTotal" class="form-label fw-bold">Monto Total</label>
        <div class="input-group">
            <span class="input-group-text">$</span>
            <input asp-for="Orden.MontoTotal" class="form-control" type="number" value=@Model.Orden.MontoTotal />
        </div>
        <span asp-validation-for="Orden.MontoTotal" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Orden.Fecha" class="form-label fw-bold">Fecha</label>
        <input asp-for="Orden.Fecha" type="date" class="form-control" />
        <span asp-validation-for="Orden.Fecha" class="text-danger"></span>
    </div>

    <div class="d-flex justify-content-center mt-3">
        @if (Model.FormAction == "Edit")
        {
            <button type="submit" class="btn btn-warning w-75">Editar</button>
        }
        else
        {
            <button type="submit" class="btn btn-success w-75">Guardar</button>
        }
    </div>

</form>

Views/OrdenDeCompra/_tableOrdenCompra.cshtml
@model IEnumerable<OrdenDeCompra>

@if (Model is not null)
{
    <div class="table-responsive-lg">
        <table id="tablaOrdenDeCompra" class="table table-striped table-hover align-middle mt-3">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Número de Orden</th>
                    <th scope="col">Proveedor</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Monto</th>
                    <th scope="col" class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (OrdenDeCompra orden in Model)
                {
                    <tr>
                        <td>@orden.Id</td>
                        <td>@orden.NumeroDeOrden</td>
                        <td>@orden.Proveedor</td>
                        <td>@orden.Fecha</td>
                        <td>$@orden.MontoTotal</td>
                        <td class="text-center">
                            <a href="/OrdenDeCompra/Edit/@orden.Id" class="btn btn-sm btn-warning">
                                <i class="bi bi-pencil-square"></i> Editar
                            </a>

                            <a href="/OrdenDeCompra/Delete/@orden.Id" class="btn btn-sm btn-danger ms-1">
                                <i class="bi bi-trash"></i> Eliminar
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

}

Views/Shared/_Alerts.cshtml
<div id="floatingAlerts" class="alert-container position-fixed top-0 start-50 translate-middle-x p-3 alert-style">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show shadow" role="alert">
            @TempData["SuccessMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show shadow" role="alert">
            @TempData["ErrorMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD Construplan</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/construplan_examen.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.4.1/css/responsive.bootstrap5.min.css">
</head>

<body>
    <header class="bg-warning">
        <nav class="navbar navbar-expand-md navbar-light bg-warning border-bottom shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center"
                   asp-controller="OrdenDeCompra" asp-action="Index">
                    <img src="/img/logoConstruplan.png" class="img-fluid" style="max-height:45px;" alt="Construplan" />
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navMenu">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-controller="OrdenDeCompra" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark fw-bold" asp-controller="OrdenDeCompra" asp-action="Create">Crear</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @await Html.PartialAsync("_Alerts")
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - construplan_examen
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.4.1/js/responsive.bootstrap5.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>